

services:
  prod-redis:
    image: redis:7-alpine
    container_name: production_redis
    restart: always
    ports:
      - "6379:6379" # Accessible locally on the server machine
    volumes:
      - redis-data:/data

  prod-mongo:
    image: mongo:8
    container_name: production_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: YourVerySecurePassword Here
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:
