events {}

http {

  server {

    listen 80;

    location /api {
      proxy_pass http://api:5000;
    }

    location / {
      proxy_pass http://web:4173;
    }

    location /admin {
      proxy_pass http://admin:4174;
    }

  }

}